# Generated by Django 5.0.6 on 2024-07-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nota",
            name="titulo",
            field=models.CharField(max_length=100, verbose_name="Título da nota"),
        ),
    ]
